"""add mpesa fields

Revision ID: ae11fe7dff70
Revises: cb01140ed88a
Create Date: 2026-04-18 00:04:28.451378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae11fe7dff70'
down_revision = 'cb01140ed88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_channel', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('till_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('paybill_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('account_reference', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('account_reference')
        batch_op.drop_column('paybill_number')
        batch_op.drop_column('till_number')
        batch_op.drop_column('payment_channel')

    # ### end Alembic commands ###
