"""add tier and period_start

Revision ID: c3778c06eb0b
Revises: e98f7944885f
Create Date: 2026-04-22 22:13:02.916495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3778c06eb0b'
down_revision = 'e98f7944885f'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Add column as NULLABLE first
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.String(20), nullable=True))

    # 2. Backfill values
    op.execute("UPDATE users SET tier = 'premium' WHERE is_premium = TRUE")
    op.execute("UPDATE users SET tier = 'free' WHERE is_premium = FALSE OR is_premium IS NULL")

    # 3. Make it NOT NULL after data is filled
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('tier', nullable=False)

    # budgets table
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period_start', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.drop_column('tier')

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_column('period_start')

    # ### end Alembic commands ###
