"""add payment_method

Revision ID: cb01140ed88a
Revises: 78f6f80b73d5
Create Date: 2026-04-16 22:51:41.512017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb01140ed88a'
down_revision = '78f6f80b73d5'
branch_labels = None
depends_on = None

def upgrade():
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))

    op.execute("UPDATE transactions SET payment_method = 'Mpesa' WHERE payment_method IS NULL")

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('payment_method', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
